### ISSUE TITLE
can't create new thread at interpreter shutdown

### ISSUE THREAD

**Issue by CantSamboAmigoD8** [lossless1024/StreaMonitor#142]
This is the issue i get. I am new to this any help would be appreciated.

Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Users\[REDACTED]\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Users\[REDACTED]\[REDACTED]\StreaMonitor\streamonitor\managers\climanager.py", line 22, in run
    reply = self.execCmd(line)
            ^^^^^^^^^^^^^^^^^^
  File "C:\Users\[REDACTED]\[REDACTED]\StreaMonitor\streamonitor\manager.py", line 30, in execCmd
    return command(streamer, username, site)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\[REDACTED]\[REDACTED]\StreaMonitor\streamonitor\manager.py", line 87, in do_start
    streamer.start()
  File "C:\Users\[REDACTED]\[REDACTED]\Local\Programs\Python\Python312\Lib\threading.py", line 992, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't create new thread at interpreter shutdown

**Comment by DerBunteBall** [comment]
Looks like a CPython regression [see this](https://github.com/python/cpython/issues/113964).

Codebase of StreaMonitor isn't compatible with 3.12.x try with 3.11.5

**Comment by CantSamboAmigoD8** [comment]
@DerBunteBall I saw that as well and havent tried it yet but  i got it running in docker which is probable better for me. thnx for response
