### ISSUE TITLE
stripchat error

### ISSUE THREAD

**Issue by Ryner95** [lossless1024/StreaMonitor#153]
>  * Serving Flask app 'streamonitor.managers.httpmanager'
 * Debug mode: off
2024-07-10 20:43:49,183 - ERROR - [SC] royalgirls_x: HTTPSConnectionPool(host='stripchat.com', port=443): Max retries exceeded with url: /api/vr/v2/models/username/royalgirls_x (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000018F479EA350>: Failed to resolve 'stripchat.com' ([Errno 11004] getaddrinfo failed)"))
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 196, in _new_conn
    sock = connection.create_connection(
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 490, in _make_request
    raise new_e
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 615, in connect
    self.sock = sock = self._new_conn()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 203, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x0000018F479EA350>: Failed to resolve 'stripchat.com' ([Errno 11004] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='stripchat.com', port=443): Max retries exceeded with url: /api/vr/v2/models/username/royalgirls_x (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000018F479EA350>: Failed to resolve 'stripchat.com' ([Errno 11004] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Biblioteca\user\Descargas\Compressed\StreaMonitor-master\StreaMonitor-master\streamonitor\bot.py", line 134, in run
    self.sc = self.getStatus()
  File "D:\Biblioteca\user\Descargas\Compressed\StreaMonitor-master\StreaMonitor-master\streamonitor\sites\stripchat.py", line 37, in getStatus
    r = requests.get('https://stripchat.com/api/vr/v2/models/username/' + self.username, headers=self.headers)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='stripchat.com', port=443): Max retries exceeded with url: /api/vr/v2/models/username/royalgirls_x (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000018F479EA350>: Failed to resolve 'stripchat.com' ([Errno 11004] getaddrinfo failed)"))
2024-07-10 20:43:49,186 - INFO - [SC] royalgirls_x: Not running

**Comment by DerBunteBall** [comment]
I guess you have an issue with your DNS resolution.

**Comment by Ryner95** [comment]
Ok thanks, I think I know what it is, I was bordering on the fact that the rest was going well, it must be the configuration of the pihole that now that I fall it doesn't let me enter stripchat.com and I need to enter through es.stripchat.com

**Comment by Ryner95** [comment]
Ok if that was it thanks.
