### ISSUE TITLE
Its not working at all

### ISSUE THREAD

**Issue by keksom** [lossless1024/StreaMonitor#162]
None of the cams are working, even though they are online it shows them as "not running".
If it helps here is what it shows after starting it:
"
>  * Serving Flask app 'streamonitor.managers.httpmanager'
 * Debug mode: off
2024-08-24 02:11:25,993 - ERROR - [C4] lynnbyrd: HTTPSConnectionPool(host='hu.cam4.com', port=443): Max retries exceeded with url: /rest/v1.0/profile/lynnbyrd/info (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001BA46ACE150>: Failed to establish a new connection: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions'))
Traceback (most recent call last):
  File "C:\Users\888\AppData\Roaming\Python\Python311\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\888\AppData\Roaming\Python\Python311\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "C:\Users\888\AppData\Roaming\Python\Python311\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
PermissionError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\888\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\888\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\888\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "C:\Users\888\AppData\Roaming\Python\Python311\site-packages\urllib3\connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "C:\Users\888\AppData\Roaming\Python\Python311\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001BA46ACE150>: Failed to establish a new connection: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\888\AppData\Roaming\Python\Python311\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\888\AppData\Roaming\Python\Python311\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\888\AppData\Roaming\Python\Python311\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='hu.cam4.com', port=443): Max retries exceeded with url: /rest/v1.0/profile/lynnbyrd/info (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001BA46ACE150>: Failed to establish a new connection: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\888\P2\StreaMonitor-master\streamonitor\bot.py", line 134, in run
    self.sc = self.getStatus()
              ^^^^^^^^^^^^^^^^
  File "D:\888\P2\StreaMonitor-master\streamonitor\sites\cam4.py", line 22, in getStatus
    r = requests.get(f'https://hu.cam4.com/rest/v1.0/profile/{self.username}/info', headers=headers)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\888\AppData\Roaming\Python\Python311\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\888\AppData\Roaming\Python\Python311\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\888\AppData\Roaming\Python\Python311\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\888\AppData\Roaming\Python\Python311\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\888\AppData\Roaming\Python\Python311\site-packages\requests\adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='hu.cam4.com', port=443): Max retries exceeded with url: /rest/v1.0/profile/lynnbyrd/info (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001BA46ACE150>: Failed to establish a new connection: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions'))
2024-08-24 02:11:26,000 - INFO - [C4] lynnbyrd: Not running
"

**Comment by lossless1024** [comment]
This is your error in the logs: 
PermissionError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

So it seems the app does not have enough permissions to save to the folder you use
