### ISSUE TITLE
RuntimeError: No active exception to reraise

### ISSUE THREAD

**Issue by TeslaLyon** [lossless1024/StreaMonitor#40]
2022-11-24 21:46:51,713 - INFO - [BC] Torysexs: Channel online
2022-11-24 21:46:51,713 - INFO - [BC] Torysexs: Started downloading show
Exception in thread Thread-111 (execute):
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/liangshuo/code/py-project/StreaMonitor/streamonitor/downloaders/ffmpeg.py", line 45, in execute
    raise
RuntimeError: No active exception to reraise
Exception in thread Thread-112 (execute):
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/liangshuo/code/py-project/StreaMonitor/streamonitor/downloaders/ffmpeg.py", line 45, in execute
    raise
RuntimeError: No active exception to reraise
Exception in thread Thread-113 (execute):
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/liangshuo/code/py-project/StreaMonitor/streamonitor/downloaders/ffmpeg.py", line 45, in execute
    raise
RuntimeError: No active exception to reraise

**Comment by TeslaLyon** [comment]
ffmpeg version 5.1.2

**Comment by TeslaLyon** [comment]
I don't know the reason, but after I reinstalled ffmpeg, no error was reported.

**Comment by JuslikeWind** [comment]
> I don't know the reason, but after I reinstalled ffmpeg, no error was reported.

Win11 still have the problem. On linux I met ConnectionResetError: [Errno 104] Connection reset by peer.

**Comment by DerBunteBall** [comment]
This occures when the if statement in line 44 of ffmpeg.py fails. So the returncode is set but not 0 or 255.

The RuntimeError is occuring because ```python raise``` get's no Exception assigned explicitly.

So we want to know what's the value of returncode. So you could try to implement a little silly exception which gives us this info like this:

```python
class DownloaderException(Exception):
    pass
```

Then our if and raise looks like this:

```python
if process.returncode and process.returncode != 0 and process.returncode != 255:
    raise DownloaderException("Returncode is: "+str(process.returncode))
```
Always check that your ffmpeg build is correct, in your path and if needed emulate a download process manually.

Best Regards

**Comment by JuslikeWind** [comment]
> This occures when the if statement in line 44 of ffmpeg.py fails. So the returncode is set but not 0 or 255.
> 
> The RuntimeError is occuring because `python raise` get's no Exception assigned explicitly.
> 
> So we want to know what's the value of returncode. So you could try to implement a little silly exception which gives us this info like this:
> 
> ```python
> class DownloaderException(Exception):
>     pass
> ```
> 
> Then our if and raise looks like this:
> 
> ```python
> if process.returncode and process.returncode != 0 and process.returncode != 255:
>     raise DownloaderException("Returncode is: "+str(process.returncode))
> ```
> 
> Always check that your ffmpeg build is correct, in your path and if needed emulate a download process manually.
> 
> Best Regards

the returncode is 1

**Comment by DerBunteBall** [comment]
This should indicate that the ffmpeg startup fails.

When you open a PowerShell. In Search at Dashbaord -> PowerShell does this work:

```
ffmpeg -version
```

Best Regards

**Comment by JuslikeWind** [comment]
> This should indicate that the ffmpeg startup fails.
> 
> When you open a PowerShell. In Search at Dashbaord -> PowerShell does this work:
> 
> ```
> ffmpeg -version
> ```
> 
> Best Regards

PS C:\Users\10108> ffmpeg -version
ffmpeg version 5.1.2-full_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
built with gcc 12.1.0 (Rev2, Built by MSYS2 project)
configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
libavutil      57. 28.100 / 57. 28.100
libavcodec     59. 37.100 / 59. 37.100
libavformat    59. 27.100 / 59. 27.100
libavdevice    59.  7.100 / 59.  7.100
libavfilter     8. 44.100 /  8. 44.100
libswscale      6.  7.100 /  6.  7.100
libswresample   4.  7.100 /  4.  7.100
libpostproc    56.  6.100 / 56.  6.100

**Comment by DerBunteBall** [comment]
Which site do you want? So we need to do a manual run to figure out whether something here fails.

Best Regards

**Comment by JuslikeWind** [comment]
Bongacams and its look-like

**Comment by JuslikeWind** [comment]
You can use en.porndig.club to have a try which iI prefer. Though it's actually Bongacams.

**Comment by DerBunteBall** [comment]
It seems that bongacams work.

I wrote a little script which does the same like the extractor and downloader does (without quality selection) and ffmpeg runs normal.

You can try with this: https://gist.github.com/DerBunteBall/96616c1d26287a63530f57772ebc041e

Run this:

```
python3.exe bc.py username
```

I took one from the site you posted and it starts ffmpeg normally. Keep in mind: There is no stdin and stdout handling. So eventually you need to kill ffmpeg seperately. Model needs to be online and public no checking for that.

Best Regards

**Comment by JuslikeWind** [comment]
> It seems that bongacams work.
> 
> I wrote a little script which does the same like the extractor and downloader does (without quality selection) and ffmpeg runs normal.
> 
> You can try with this: https://gist.github.com/DerBunteBall/96616c1d26287a63530f57772ebc041e
> 
> Run this:
> 
> ```
> python3.exe bc.py username
> ```
> 
> I took one from the site you posted and it starts ffmpeg normally. Keep in mind: There is no stdin and stdout handling. So eventually you need to kill ffmpeg seperately. Model needs to be online and public no checking for that.
> 
> Best Regards

well thanks, but...
![image](https://user-images.githubusercontent.com/44227104/203861235-eceefa2b-fe54-42e5-94bf-621107c9a9be.png)
![image](https://user-images.githubusercontent.com/44227104/203861284-d00384fb-188d-4c7e-b68a-d550b9ccd524.png)

**Comment by DerBunteBall** [comment]
Ah... Ok.

Looks like connection problems. They seem to occur shortly after connection was established.

Two things are possible I think:

1. Your TLS/SSL Library is broken. Becasue it's a python 3.11 I ton't think so. Also that wouldn't explain why the connection frist gets opened. Often broen TLS stuff prevents a connection.
2. Some system in the middle does stuff with the connection (e.g. DPI stuff).

The Browser should have similar problems unless there is something like a Proxy activated when it's option 2.

It's an error comming from Windows becasue the underlying conneciton gets closed.

**Comment by JuslikeWind** [comment]
> Ah... Ok.
> 
> Looks like connection problems. They seem to occur shortly after connection was established.
> 
> Two things are possible I think:
> 
>     1. Your TLS/SSL Library is broken. Becasue it's a python 3.11 I ton't think so. Also that wouldn't explain why the connection frist gets opened. Often broen TLS stuff prevents a connection.
> 
>     2. Some system in the middle does stuff with the connection (e.g. DPI stuff).
> 
> 
> The Browser should have similar problems unless there is something like a Proxy activated when it's option 2.
> 
> It's an error comming from Windows becasue the underlying conneciton gets closed.

Hi, I am back. Finally I give up Windows and turn to Ubuntu, now the problem is still connection as follow:

`2022-11-25 21:13:53,995 - ERROR - [PD] Nateley-ice: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Traceback (most recent call last):
  File "/home/feng/envs/StreaMonitor/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/feng/envs/StreaMonitor/lib/python3.8/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/feng/envs/StreaMonitor/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/feng/envs/StreaMonitor/lib/python3.8/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/home/feng/envs/StreaMonitor/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/home/feng/envs/StreaMonitor/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/feng/envs/StreaMonitor/lib/python3.8/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/feng/envs/StreaMonitor/lib/python3.8/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/feng/envs/StreaMonitor/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/feng/envs/StreaMonitor/lib/python3.8/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/home/feng/envs/StreaMonitor/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/feng/envs/StreaMonitor/lib/python3.8/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/feng/envs/StreaMonitor/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/feng/envs/StreaMonitor/lib/python3.8/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/home/feng/envs/StreaMonitor/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/home/feng/envs/StreaMonitor/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/feng/projects/StreaMonitor/streamonitor/bot.py", line 110, in run
    self.sc = self.getStatus()
  File "/home/feng/projects/StreaMonitor/streamonitor/sites/porndig.py", line 37, in getStatus
    if len(r.text) == 25 or r.status_code == 404:
  File "/home/feng/envs/StreaMonitor/lib/python3.8/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/feng/envs/StreaMonitor/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/feng/envs/StreaMonitor/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/feng/envs/StreaMonitor/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/feng/envs/StreaMonitor/lib/python3.8/site-packages/requests/adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))`

Could you give me some advice to handle this？ It's about to SUCCESS!

**Comment by DerBunteBall** [comment]
It's infact the same error only with another appearance. The WinError 10054 exactly tells this the appearance on the TLS level in ffmpeg can be related to the technical design on Windows.

That makes clear that your network/ISP is the problem. The only solution would be a VPN with a unfiltered IP. I think it's a DPI system at the ISP which prevents constant connections (due to filter stuff or technical crap).

**Comment by JuslikeWind** [comment]
> It's infact the same error only with another appearance. The WinError 10054 exactly tells this the appearance on the TLS level in ffmpeg can be related to the technical design on Windows.
> 
> That makes clear that your network/ISP is the problem. The only solution would be a VPN with a unfiltered IP. I think it's a DPI system at the ISP which prevents constant connections (due to filter stuff or technical crap).

Thank you very much! I finally did it.

The problem is still ffmpeg. I compiled ffmpeg without HTTP configuration(No HTTP PROTOCOL), so HTTP connection always reported error.

This time I recompile ffmpeg with configuration --enable-openssl. The problem is solved.NO ERROR ANY MORE!

So the fact is that the platform doesn't matter. I really went a looooooooong road round.

**Comment by DerBunteBall** [comment]
> > It's infact the same error only with another appearance. The WinError 10054 exactly tells this the appearance on the TLS level in ffmpeg can be related to the technical design on Windows.
> > That makes clear that your network/ISP is the problem. The only solution would be a VPN with a unfiltered IP. I think it's a DPI system at the ISP which prevents constant connections (due to filter stuff or technical crap).
> 
> Thank you very much! I finally did it.
> 
> The problem is still ffmpeg. I compiled ffmpeg without HTTP configuration(No HTTP PROTOCOL), so HTTP connection always reported error.
> 
> This time I recompile ffmpeg with configuration --enable-openssl. The problem is solved.NO ERROR ANY MORE!
> 
> So the fact is that the platform doesn't matter. I really went a looooooooong road round.

When ffmpeg were compiled without TLS/SSL that of course wouldn't work.

You can just use the Distro packages from apt.

That's just ```apt-get install ffmpeg``` they are new enough for everyting.

Windows builds can be found here: https://www.gyan.dev/ffmpeg/builds/

These versions work fine. So to compile it your self really needs a good reason normally.

Best Regards
