### ISSUE TITLE
not running

### ISSUE THREAD

**Issue by nsa5574** [lossless1024/StreaMonitor#46]
so I added a few streams to check if it works but it shows they aren't running when I go to the site they are online, it also shows this for every stream.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nsa\Desktop\THE RECORD\StreaMonitor-master\streamonitor\bot.py", line 110, in run
    self.sc = self.getStatus()
              ^^^^^^^^^^^^^^^^
  File "C:\Users\nsa\Desktop\THE RECORD\StreaMonitor-master\streamonitor\sites\stripchat.py", line 17, in getStatus
    r = requests.get('https://stripchat.com/api/vr/v2/models/username/' + self.username, headers=self.headers)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nsa\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nsa\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nsa\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nsa\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='stripchat.com', port=443): Max retries exceeded with url: /api/vr/v2/models/username/Avril_Cyrus (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D4C4D57C50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

**Comment by DerBunteBall** [comment]
That's an connection error ralted to your network. The StripChat Request works (tested a few minutes ago).

Reasons can be: Proxies, DNS, DPI at ISP.

**Comment by nsa5574** [comment]
do you know how i can resolve it?

**Comment by nsa5574** [comment]
can i change the url from stripchat.com to stripchat.global ?

**Comment by DerBunteBall** [comment]
You could change it in the extractor.

But you also could set the IPs in your Hosts file. If stripchat.com and stripchat.gloabal makes a difference this indidcates that your DNS server makes silly things.

They resolve to the same IPs which are Cloud Provider IPs.
