### ISSUE TITLE
while adding streamate account -> TypeError: unsupported operand type(s) for |: 'dict' and 'dict'  

### ISSUE THREAD

**Issue by keeskroket** [lossless1024/StreaMonitor#60]
Hi, 

when adding a streamate account I get the error message below, any idea whats going wrong? 

2023-02-13 23:50:07,152 - ERROR - [SM] https://streamate.com/cam/Gina_Gold: unsupported operand type(s) for |: 'dict' and 'dict'
Traceback (most recent call last):
  File "/home/xxxx/stream/StreaMonitor/streamonitor/bot.py", line 125, in run
    self.sc = self.getStatus()
  File "/home/xxxx/stream/StreaMonitor/streamonitor/sites/streamate.py", line 21, in getStatus
    headers = self.headers | {
TypeError: unsupported operand type(s) for |: 'dict' and 'dict'

**Comment by DerBunteBall** [comment]
Which Python Version do you use?

That's a failing operation on two dictonaries. Most likely something like this occurs because the Python version doesn't support this. The codebase has no special handling for different Python versions. So it's likely that the codebase only works with very recent versions.

**Comment by DerBunteBall** [comment]
Works on fresh pyenv based on 3.11.1

```
> add Gina_Gold SM
2023-02-14 00:15:28,067 - INFO - manager_cli: Added [SM] Gina_Gold
2023-02-14 00:15:32,446 - INFO - [SM] Gina_Gold: Channel online
2023-02-14 00:15:32,446 - INFO - [SM] Gina_Gold: Selected 1280x720 resolution
2023-02-14 00:15:32,446 - INFO - [SM] Gina_Gold: Started downloading show
> 
```

Check your Python version.

**Comment by keeskroket** [comment]
Thank you for answering, I updated my python version to 3.11.1 and it works fine!
