### ISSUE TITLE
Error on starting downloader.py

### ISSUE THREAD

**Issue by cimboxli** [lossless1024/StreaMonitor#64]
I keeping running into this error message when running the downloader

Traceback (most recent call last):
  File "/Volumes/Supply/_Inbox-Media/StreaMonitor/Downloader.py", line 9, in <module>
    import streamonitor.sites  # must have
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Supply/_Inbox-Media/StreaMonitor/streamonitor/sites/__init__.py", line 7, in <module>
    from . import *
AttributeError: partially initialized module 'streamonitor.sites' has no attribute '' (most likely due to a circular import)

**Comment by baselqt** [comment]
here's how i did it:

first download python from the official website then install it 

then make sure to run command prompt / powershell as administrator (very important)

download the zip file of this code then extract it 

make sure to change the path in the command prompt to the path inside the folder with the cd command (notice :command prompt/powershell is opened as administrator, and the path must lead to the content inside the folder not lead to the main folder itself, it contains 3 folders and 11 files) 
for the above step if you didnt know how to do it then just cut paste the folder's content in c/users/your username .    (notice :if you placed them here then make sure you placed the 11 files,3 folders of this code, dont place the main folder that contains these).

once youre done and the command prompt or powershell's path is leading to the files and folders, type in these commands (all of them... use them one by one)

python -m pip install requests 

python -m pip install terminaltables

python -m pip install pyzmq

python -m pip install flask 

python -m pip install termcolor 

python -m pip install beautifulsoup4 

python -m pip install websocket-client

python -m pip install ffmpy 

python -m pip install m3u8 

ONCE YOU DID ALL OF THESE YOU ARE DONE.

to use it:
open file explorer in the location inside the file (same as before where there are 11 files)

then right click on an empty area and click open in terminal..
the windows powershell will open if you are on windows 11 and the command prompt will open if you are on windows 10 .

type:  python Downloader.py 

done. its open now you can use alle the commands that were specified by the creator like for example :

add Alanna_01_ sc 

this will start recording alanna_01 from stripchat and it will add the streamer in the streamers list 

once you added all your streamers you can type: start *
to start recording all live models. 
if you want to record a model  that you added to the list use:
start modelname 
for example start Alanna_01_ 


to see your list of models, type : status .

hope this helps :) if it helped please let me know

**Comment by DerBunteBall** [comment]
Such errors are often related to cache stuff. Clear the python cache files e.g. in ```__pycache__``` folder and try again.

Also try to setup a virtual environment. On macOS everything can be found in Homebrew. I think it's a Mac because of ```/Volumes/...``` mountpoint.

**Comment by baselqt** [comment]
an error similar to this actually appeared to me and it seems that it was happening because I didn't install all pip because the pip got corrupted while updating it

it got corrupted because i was updating without running it as administrator 

i ran it as admin and fixed the pip with python -m ensurepip 

then i installed all the requirements and it worked just fine
